version: '3.8'

services:
  mariadb:
    image: mariadb:10.11
    container_name: mariadb_db
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: biblioYaniraV
      MARIADB_USER: usuario
      MARIADB_PASSWORD: usuario123
    ports:
      - "3307:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./initMariaDB.sql:/docker-entrypoint-initdb.d/initMariaDB.sql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    ports:
      - "8080:80"

volumes:
  mariadb_data:
